### ISSUE TITLE
support new response format & feature

### ISSUE THREAD

**Issue by VictoriqueMoe** [waifuvault/waifuVault-csharp-api#3]
there are 2 changes to be made.

## First

the first is the `WaifuResponse` has moved `protected` and `hideFilename` into it's own settings object that looks as followes: 

![image](https://github.com/waifuvault/waifuVault-csharp-api/assets/27996712/68afb4cb-a249-4b49-99b3-9594a94687ab)

You can check the swagger schema for this change here: https://waifuvault.moe/api-docs/

![image](https://github.com/waifuvault/waifuVault-csharp-api/assets/27996712/36aa319f-f26d-48e8-85e0-eb34d8a2f5bd)

this object can not be null and will ALWAYS contain the values inside of it

## Second

The second change is in the upload query parameters, there is a new optional boolean called `one_time_download`. you can see this reflected here: 
![image](https://github.com/waifuvault/waifuVault-csharp-api/assets/27996712/7109097d-6d02-4d7e-a752-54d51fc2b3bd)

**Comment by nakedmcse** [comment]
Completed.

https://github.com/waifuvault/waifuVault-csharp-api/commit/b0b0be824d6f64487adfea3f3c1eeab60e2ee8ff
