### ISSUE TITLE
deleteFile throws exception with invalid token

### ISSUE THREAD

**Issue by weddleben** [waifuvault/waifuVault-csharp-api#7]
the `Waifuvault.Api.deleteFile` function throws an exception if an invalid token is passed. Should the function be handled differently? Or should there be a note in the [documentation](https://github.com/waifuvault/waifuVault-csharp-api?tab=readme-ov-file#delete-file)?

````bash
Unhandled exception. System.Exception: Error BadRequest (BAD_REQUEST:Unknown token notARealToken123)
````

the `Waifuvault.Api.deleteBucket` behaves the same:
````bash
Unhandled exception. System.Exception: Error BadRequest (BAD_REQUEST:Unable to delete bucket with token fakeBucketToken)
````

**Comment by nakedmcse** [comment]
This is expected behaviour for delete - if you supply a bad token, it throws an exception.  I will add a note to the readme for both.

Thanks,

**Comment by weddleben** [comment]
roger that, thank you!
